### ISSUE TITLE
When clicking plugin name in Plugins tab, game crashes

### ISSUE THREAD

**Issue by ipehrson** [esnar11/SkipReplay#3]
I installed this app for the first time today, tried to go into bakkesmod plugins tab to configure the SkipReplay. I did this twice and the game crashed each time.

**Comment by luukvbaal** [comment]
Thanks for reporting, I pushed a fix to github and bakkesplugins. I'll close the issue when they uploaded the new version to bakkesplugins.com

**Comment by ipehrson** [comment]
Awesome, I just built it locally and it works great. Great plugin!

**Comment by Remonell** [comment]
> Thanks for reporting, I pushed a fix to github and bakkesplugins. I'll close the issue when they uploaded the new version to bakkesplugins.com

How long do you think this will take bakkesplugins to update?

**Comment by luukvbaal** [comment]
> How long do you think this will take bakkesplugins to update?

By [their](https://wiki.bakkesplugins.com/useful_info/submitting_to_bakkesplugins/) estimate: "It may take a couple days to a couple weeks depending on moderator availability."

**Comment by FrankMormino** [comment]
Thanks i legit just ran into this issue and awesome to see how fast turn around was - hopefully they will be as responsive as you were. Cheers!
